app:
  name: "OptimizedSparkETL"
  log_level: "INFO"

spark:
  master: "local[*]"
  shuffle_partitions: 50
  adaptive_execution: true
  driver_memory: "4g"
  executor_memory: "8g"

database:
  host: "localhost"
  port: 3306
  name: "data_db"
  user: "root"
  password: "root"
  jdbc_params:
    serverTimezone: "UTC"
    useSSL: false
    allowPublicKeyRetrieval: true
    rewriteBatchedStatements: true
    cachePrepStmts: true
    prepStmtCacheSize: 512
    prepStmtCacheSqlLimit: 4096
    useServerPrepStmts: true
    connectTimeout: 10000
    socketTimeout: 60000
    autoReconnect: true

paths:
  mysql_driver: "libs/mysql-connector-j-8.0.31.jar"
  input_file: "data/sample.csv"